'use client';

import React, { useState } from 'react';
import { ArrowRight, BriefcaseBusiness, Check, CheckCircle2, ChevronDown, ChevronUp, Gauge, Lightbulb, Mail, MapPin, PenTool, RefreshCw, Sparkles, Target, TrendingUp, TriangleAlert, WandSparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import { JobAgentResponse } from '@/types';

interface JobAnalysisDashboardProps { data?: JobAgentResponse | null; onReset?: () => void; onTailorResume?: () => void; onGenerateCoverLetter?: () => void; }
const percentage = (value: number | undefined, fallback: number) => value === undefined || value === null ? fallback : Math.max(0, Math.min(100, Math.round(value <= 1 ? value * 100 : value)));

export const JobAnalysisDashboard: React.FC<JobAnalysisDashboardProps> = ({ data, onReset, onTailorResume, onGenerateCoverLetter }) => {
  const [showResponsibilities, setShowResponsibilities] = useState(false);
  const job = data?.job;
  const match = data?.match;
  const matchScore = percentage(match?.score, 58);
  const similarityScore = percentage(match?.similarity, 56);
  const keywordScore = Math.min(100, Math.round(matchScore * 1.06));
  const matchedSkills = match?.matched_skills?.length ? match.matched_skills : ['Python', 'Docker', 'Git', 'LangChain', 'REST API', 'SQL'];
  const missingSkills = match?.missing_skills?.length ? match.missing_skills : ['AWS', 'Kubernetes', 'CI/CD', 'Terraform'];
  const recommendations = match?.recommendations?.length ? match.recommendations : [`Make ${matchedSkills.slice(0, 3).join(', ')} prominent in your summary.`, `Only add ${missingSkills.slice(0, 2).join(' or ')} where you have genuine experience.`];
  const scoreColor = matchScore >= 75 ? '#34d399' : matchScore >= 50 ? '#fbbf24' : '#fb7185';
  const alignment = matchScore >= 75 ? 'Strong alignment' : matchScore >= 50 ? 'Promising alignment' : 'Needs tailoring';

  return <div className="min-h-screen bg-[#f7f8fc] text-slate-900 selection:bg-violet-200">
    <div className="absolute inset-x-0 top-0 h-[390px] overflow-hidden bg-slate-950"><div className="absolute -top-28 left-[8%] h-96 w-96 rounded-full bg-violet-600/30 blur-[110px]" /><div className="absolute right-[10%] top-8 h-72 w-72 rounded-full bg-cyan-500/20 blur-[100px]" /><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(#94a3b8_1px,transparent_1px)] [background-size:22px_22px]" /></div>
    <header className="relative z-10 border-b border-white/10"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3 text-white"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-violet-400 to-fuchsia-500 shadow-lg shadow-violet-500/25"><Sparkles className="h-5 w-5" /></div><div><p className="font-heading text-lg font-extrabold tracking-tight">ApplyAI</p><p className="text-[11px] font-medium text-slate-400">Application intelligence</p></div></div>{onReset && <button onClick={onReset} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-3.5 py-2 text-xs font-semibold text-slate-200 transition hover:bg-white/10"><RefreshCw className="h-3.5 w-3.5" />New analysis</button>}</div></header>
    <main className="relative z-10 mx-auto max-w-7xl px-5 pb-16 pt-8 lg:px-8">
      <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="mb-7 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div className="text-white"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-300/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.16em] text-violet-200"><WandSparkles className="h-3.5 w-3.5" />Analysis complete</div><h1 className="max-w-3xl font-heading text-3xl font-extrabold tracking-tight sm:text-4xl">{job?.title || 'Senior Developer'}</h1><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-300"><span className="flex items-center gap-1.5 font-semibold text-white"><BriefcaseBusiness className="h-4 w-4 text-violet-300" />{job?.company || 'HCLTech'}</span><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4 text-slate-400" />{job?.location || 'Location not specified'}</span></div></div><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100"><p className="text-[10px] font-bold uppercase tracking-widest text-emerald-300">Recommendation</p><p className="mt-1 font-semibold">{alignment}</p></div></motion.section>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_310px]"><div className="space-y-6">
        <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 }} className="grid gap-4 sm:grid-cols-3"><ScoreCard label="Overall match" value={matchScore} color={scoreColor} icon={<Target className="h-4 w-4" />} primary /><ScoreCard label="Semantic fit" value={similarityScore} color="#818cf8" icon={<TrendingUp className="h-4 w-4" />} /><ScoreCard label="Keyword coverage" value={keywordScore} color="#22d3ee" icon={<Gauge className="h-4 w-4" />} /></motion.section>
        <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.14 }} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_15px_35px_-25px_rgba(15,23,42,0.35)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-600">Skills intelligence</p><h2 className="mt-1 font-heading text-xl font-extrabold">Your strongest evidence</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">{matchedSkills.length} matched · {missingSkills.length} to address</span></div><div className="mt-6 grid gap-6 md:grid-cols-2"><SkillGroup title="Already demonstrated" skills={matchedSkills} good /><SkillGroup title="Opportunities to address" skills={missingSkills} /></div></motion.section>
        <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_15px_35px_-25px_rgba(15,23,42,0.35)] sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><Lightbulb className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-amber-600">Next best actions</p><h2 className="font-heading text-xl font-extrabold">How to improve this application</h2></div></div><div className="mt-5 grid gap-3">{recommendations.slice(0, 3).map((item, index) => <div key={item} className="flex gap-3 rounded-2xl bg-slate-50 p-4"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">{index + 1}</span><p className="pt-0.5 text-sm leading-6 text-slate-600">{item}</p></div>)}</div></motion.section>
      </div><aside className="space-y-6"><motion.section initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.16 }} className="overflow-hidden rounded-3xl bg-slate-900 p-5 text-white shadow-xl shadow-slate-300/50"><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-300">Match profile</p><div className="mt-5 space-y-4"><Metric label="Skills match" value={matchScore} color="bg-emerald-400" /><Metric label="Keyword signal" value={keywordScore} color="bg-cyan-400" /><Metric label="Context alignment" value={similarityScore} color="bg-violet-400" /></div><div className="mt-6 border-t border-white/10 pt-5 text-sm leading-6 text-slate-300">A tailored resume makes your most relevant experience easier to find.</div></motion.section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_15px_35px_-25px_rgba(15,23,42,0.35)]"><button onClick={() => setShowResponsibilities(!showResponsibilities)} className="flex w-full items-center justify-between text-left"><span><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Role brief</p><h2 className="mt-1 font-heading text-lg font-extrabold">Job overview</h2></span>{showResponsibilities ? <ChevronUp className="h-5 w-5 text-slate-400" /> : <ChevronDown className="h-5 w-5 text-slate-400" />}</button><p className="mt-4 text-sm leading-6 text-slate-600">{job?.summary || 'Review the role requirements and tailor the application around your strongest relevant experience.'}</p>{showResponsibilities && <ul className="mt-4 space-y-2 border-t border-slate-100 pt-4">{(job?.responsibilities || []).map((item) => <li key={item} className="flex gap-2 text-sm leading-5 text-slate-600"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />{item}</li>)}</ul>}</section></aside></div>
      <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.28 }} className="mt-6 overflow-hidden rounded-3xl bg-gradient-to-r from-violet-700 via-indigo-700 to-slate-900 p-6 text-white shadow-xl shadow-violet-200 sm:flex sm:items-center sm:justify-between sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-violet-200">Ready for the next step?</p><h2 className="mt-1 font-heading text-2xl font-extrabold">Turn this analysis into an application.</h2><p className="mt-2 text-sm text-indigo-100">Use the role requirements to personalize your resume and cover letter.</p></div><div className="mt-5 flex flex-wrap gap-3 sm:mt-0"><button onClick={onTailorResume} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-violet-800 transition hover:bg-violet-50"><PenTool className="h-4 w-4" />Tailor resume<ArrowRight className="h-4 w-4" /></button><button onClick={onGenerateCoverLetter} className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold transition hover:bg-white/15"><Mail className="h-4 w-4" />Cover letter</button></div></motion.section>
    </main>
  </div>;
};

function ScoreCard({ label, value, color, icon, primary = false }: { label: string; value: number; color: string; icon: React.ReactNode; primary?: boolean }) { return <div className={`rounded-3xl border p-5 ${primary ? 'border-violet-200 bg-gradient-to-br from-violet-50 to-white' : 'border-slate-200 bg-white'} shadow-[0_15px_35px_-25px_rgba(15,23,42,0.35)]`}><div className="flex items-center justify-between text-slate-500"><span className="text-xs font-bold uppercase tracking-[0.12em]">{label}</span><span style={{ color }}>{icon}</span></div><div className="mt-5 flex items-end justify-between"><span className="font-heading text-4xl font-extrabold tracking-tight">{value}%</span><span className="mb-1 text-xs font-semibold text-slate-400">out of 100</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${value}%`, backgroundColor: color }} /></div></div>; }
function SkillGroup({ title, skills, good = false }: { title: string; skills: string[]; good?: boolean }) { return <div><div className={`mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] ${good ? 'text-emerald-700' : 'text-amber-700'}`}>{good ? <CheckCircle2 className="h-4 w-4" /> : <TriangleAlert className="h-4 w-4" />}{title}</div><div className="flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${good ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-amber-200 bg-amber-50 text-amber-800'}`}>{skill}</span>)}</div></div>; }
function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <div><div className="mb-1.5 flex justify-between text-xs font-medium text-slate-300"><span>{label}</span><span className="font-bold text-white">{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>; }
